language: node_js

node_js:
  - "0.12"
  - "0.10"

branches:
  only:
    - master
    - kraken

before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh"

env:
  - LAIKA_OPTIONS="-t 5000"

notifications:
  irc:
    channels:
      - "irc.esper.net#pufferpanel"
    template:
      - "%{branch} (%{commit}): %{message} %{build_url}"
    skip_join: true

sudo: false